### ISSUE TITLE
Show total disk space saved by deleting files

### ISSUE THREAD

**Issue by NPN** [holmgr/cargo-sweep#10]
It would be nice to see how much disk space is or would be saved by running a sweep. For example, you might keep fewer days (at the cost of more recompiling later) if you really need to save disk space.

**Comment by holmgr** [comment]
Sounds like a good idea! Should not be that hard to add that as a default output, i.e both to dry-runs but also to the normal cleaning output.

Will try to have this out this weekend as part of 0.3.0 which I am currently working on :)
