### ISSUE TITLE
Deprecated/unmaintained dependencies and other issues

### ISSUE THREAD

**Issue by DuckDuckWhale** [holmgr/cargo-sweep#110]
failure is deprecated and unmaintained: https://github.com/rust-lang-deprecated/failure/pull/347

Other issues found via cargo-audit seems to be solved on the newest commit, however there isn't a new crates.io release. There's still one issue left though:

```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 570 security advisories (from /home/jason/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (145 crate dependencies)
Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.29
    └── fern 0.5.9
        └── cargo-sweep 0.6.2

error: 1 vulnerability found!
```

This remaining one can be resolved by updating to the newest fern version.

**Comment by marcospb19** [comment]
Thanks, I'll postpone 0.7.0 until I take a better look at this.

**Comment by marcospb19** [comment]
Hey, we're not using `failure`, right? So it's just the `fern` problem.
