### ISSUE TITLE
Set crates.io categories

### ISSUE THREAD

**Issue by LeoniePhiline** [holmgr/cargo-sweep#123]
Cargo sweep does not show up in the [category listing for "cargo plugins"](https://crates.io/categories/development-tools::cargo-plugins).

To fix, add to `Cargo.toml`:

```toml
categories = [
    "development-tools",
    "development-tools::cargo-plugins",
]
```

**Comment by marcospb19** [comment]
I believe `"development-tools::cargo-plugins"` already includes `"development-tools"`, but I'll double check once I make a new release.

Thanks!
