### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by pzmarzly** [holmgr/cargo-sweep#24]
Right now errors seem not to be printed correctly, and cargo-sweep exits with code 0 even on error.

```text
$ cargo sweep --toolchains nightly-2019-13-13 # toolchain that does not exist
[INFO] Using specified installed toolchains: ["nightly-2019-13-13"]
[ERROR] Failed to clean "/project/target":
```

**Comment by fenhl** [comment]
Is there a way to see what's going wrong at all? I'm running into this issue on macOS.
