### ISSUE TITLE
Suport new fingerprint format.

### ISSUE THREAD

**Issue by Eh2406** [holmgr/cargo-sweep#36]
Cargo just merged a new fingerprint format in https://github.com/rust-lang/cargo/pull/8210 (look for Fingerprint changes) We should make shure we are compatible with both the old and the new formats.

**Comment by holmgr** [comment]
Sounds reasonable, maybe this is a good opportunity to add some higher level tests, to ensure that we defend against regressions on both new and old formats

**Comment by aminya** [comment]
Is this still an issue? When I use cargo-sweep, it removes the files generated by the rust-analyzer. Not sure if it is related to this

**Comment by jyn514** [comment]
I think this has been fixed, yeah.
