### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by epage** [holmgr/cargo-sweep#4]
This will be important for CIs, otherwise
- You are limited to what is in your cache
- You do extra work to be able to update it

For doing pre-build binaries, see [trust](https://github.com/japaric/trust).  The WG-CLI is [working on improving this](https://github.com/crate-ci/meta/issues/1)

**Comment by epage** [comment]
Trust is a CI template for creating pre-built binaries, uploading them to github releases, and offers a tool for downloading them.

My concern is having to do a `cargo install` during a build.  If you use the template, I can instead use the install script to download a specific version of the tools I need.

**Comment by holmgr** [comment]
Ah now I get it. You want this project to use trust to deploy pre built binaries on releases. Seems easy enough to get started :)

**Comment by Eh2406** [comment]
If this means that there is a way to use this on ci without building from scratch. then we should add instructions to the readme on how to use it.

**Comment by holmgr** [comment]
Yes I would agree, will fix it hopefully this weekend, looking at it now it might not even be working :/
