### ISSUE TITLE
`cargo sweep -d --file` removes timestamp file

### ISSUE THREAD

**Issue by Nemo157** [holmgr/cargo-sweep#40]
I expected it to be possible to do a dry-run, then an actual run afterwards, but the dry-run deleted the timestamp file so that the actual run didn't work.

**Comment by holmgr** [comment]
Sounds like something we want to fix

**Comment by marcospb19** [comment]
Note for someone who might solve this in the future, you might want to update this test too: https://github.com/holmgr/cargo-sweep/blob/fd4dc55dd89d480276aace44b1af6adeeab7ed05/tests/integration.rs#L192-L194
