### ISSUE TITLE
`-i` is broken on master

### ISSUE THREAD

**Issue by birkenfeld** [holmgr/cargo-sweep#46]
```
$ cargo run -- sweep -d -r -i      
   Compiling cargo-sweep v0.5.0 (/home/gbr/devel/ext/cargo-sweep)
    Finished dev [unoptimized + debuginfo] target(s) in 1.55s
     Running `target/debug/cargo-sweep sweep -d -r -i`
thread 'main' panicked at '--time argument missing', src/main.rs:219:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PatchMixolydic** [comment]
The panic was introduced in 4430478, which was written in response to e53601a. The combination of these seems to have effectively made the time argument required, despite it not being marked as required (ca. 037155c).

Personally, I'd expect cargo-sweep to simply not delete any files based on time if `-t` is not provided, but this might disrupt the workflow of people who have come to expect cargo-sweep to delete old files by default.

**Comment by jyn514** [comment]
This seems to be fixed on master.
