### ISSUE TITLE
`cargo sweep -i` does not detect that nightly has been updated

### ISSUE THREAD

**Issue by jhpratt** [holmgr/cargo-sweep#57]
After running `rustup update nightly`, `cargo sweep -i` does nothing. I'm not sure if it's possible to do anything in this situation, but I figure it can't hurt to ask.

**Comment by Eh2406** [comment]
If you are in a project and a new version was installed then that should work. I am not sure why it is not working. It may be #36.

**Comment by jhpratt** [comment]
Coming back to this, I'm actually unable to reproduce. Closing as such.
