### ISSUE TITLE
Maintenance status of cargo-sweep?

### ISSUE THREAD

**Issue by jyn514** [holmgr/cargo-sweep#68]
Hello @holmgr, I noticed that there haven't been any PRs merged in the past year or so, even though there are a few useful and small PRs open. Are you still interested in maintaining this tool? If not, would you consider giving it to someone else to maintain? I'm happy to volunteer, or there's https://github.com/rust-bus which maintains several other popular crates.

**Comment by holmgr** [comment]
Hi, that is a good point. I have do not really have the time (even with the low volume of maintenance) unfortunately. I think it would be great if someone else would like to maintain the project and open to suggestions. Would you like to maintain it? I think just adding you and/or other people as maintainers would be a reasonable first step?

**Comment by jyn514** [comment]
I'm happy to maintain the project :) If you give me permissions to merge PRs and publish to crates.io I can start reviewing the open PRs.

**Comment by holmgr** [comment]
There we go, now you should have maintainer access. As for creates.io I think I managed to add you as an owner, but please check. I used the same username as you have here on GitHub. if that is incorrect I'll update

**Comment by jyn514** [comment]
Amazing, thank you! I'm quite busy this week with Rustconf but I'll spend some time looking at open PRs next week :)

**Comment by jyn514** [comment]
I'm going to close this since I've started working on cargo-sweep :) thanks again for responding so promptly and making sure the library continues to be maintained!
