### ISSUE TITLE
Allow `--maxsize` to accept byte size units

### ISSUE THREAD

**Issue by marcospb19** [holmgr/cargo-sweep#82]
I was making a contribution when I found this:

https://github.com/holmgr/cargo-sweep/blob/75414ca5dfd138691031c6f701fbaa350fd5b095/src/main.rs#L263-L273

This _TODO_ note is suggesting that we allow the `--maxsize` flag to expect
common byte-size units, like `"300 MB"`, `"10GB"` and `"10 GiB"`.

---

The [parse-size](https://crates.io/crates/parse-size) crate already implements the parsing needed to make this work.

EDIT: Oops, seems like [we are already using](https://github.com/holmgr/cargo-sweep/blob/75414ca5dfd138691031c6f701fbaa350fd5b095/tests/integration.rs#L97-L100) `human_size::Size` to do this kind of parsing.
EDIT2: Note that `humansize` and `human-size` are two different crates.

**Comment by jyn514** [comment]
We are using `human_size` in tests only right now. I think parsing user input is reasonable, though, I would take a PR for that.
