### ISSUE TITLE
Add a MSRV notice to the README

### ISSUE THREAD

**Issue by marcospb19** [holmgr/cargo-sweep#85]
Should we add a `Minimum Supported Rust Version` notice to the readme?

I ran [`cargo-msrv`](https://github.com/foresterre/cargo-msrv) in the project, at the time of writing (fd4dc55dd89d480276aace44b1af6adeeab7ed05) this version is `1.60.0`.

**Comment by marcospb19** [comment]
By replacing the code in this test:

https://github.com/holmgr/cargo-sweep/blob/fd4dc55dd89d480276aace44b1af6adeeab7ed05/tests/integration.rs#L126

By a small function, MSRV goes from `1.60.0` to `1.58.1`.

**Comment by jyn514** [comment]
I don't think it makes sense for cargo-sweep, for two reasons:
1. We have many dependencies, not all of which have a documented MSRV.
2. This is meant to be installed as a binary, not used as a library, so I don't expect many people to be compiling it from source once we fix https://github.com/holmgr/cargo-sweep/issues/28.

**Comment by marcospb19** [comment]
Makes sense, closing!
