### ISSUE TITLE
 Found argument '--recursive' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by Dueen** [holmgr/cargo-sweep#99]
# The recursive argument seems to not work when specifying the long-form argument. 

Machine: M1 Macbook Pro, macOS 13.2.0 Ventura

### **Expected behavior:**

Running the command
```sh
cargo sweep --recursive --time 30 path/to/project
```

does the same as
```sh
cargo sweep -r --time 30 path/to/project
```

### **Actual behavior:**

Running this command
```sh
cargo sweep --recursive --time 30 path/to/project
```
Errors out, while running the short-form of the recursive command
```sh
cargo sweep -r --time 30 path/to/project
```
succeeds.

<img width="1003" alt="Screenshot 2023-02-16 at 10 34 46" src="https://user-images.githubusercontent.com/42207398/219394352-e099bad4-a064-4c56-980f-124fde53c6db.png">

**Comment by marcospb19** [comment]
@Dueen what's the output of `cargo sweep --version`?
This is working fine to me at the latest version (at the time of writing) `0.6.2`.

**Comment by Dueen** [comment]
@marcospb19 Yep, I am on v0.6.2 from crates.io

**Comment by Expurple** [comment]
@jyn514, is there a reason why there still haven't been any new releases on crates.io? I've just discovered this awesome tool, encountered the same issue and resorted to `cargo install cargo-sweep --git https://github.com/holmgr/cargo-sweep.git`. But not every potential user may come up with this on the spot. And the README still recommends plain `cargo install cargo-sweep`, which installs a 2.5 year old version.

**Comment by marcospb19** [comment]
> The crates.io page gives a wrong impression that the project is unmaintained.

Indeed, this project had some maintenance hiccups, I'm now the new main maintainer :wave::smiley:.

Thank you for the bump! I'll prioritize making a new release this week!

**Comment by Expurple** [comment]
@marcospb19, thanks. Can you also add a section like "Maintainers" to the README then? I wasn't quite sure when I was tagging Jynn

**Comment by marcospb19** [comment]
Thanks for the patience guys, new release made and available on crates.io :wink:, cheers!
